name: Build WASM Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUST_LOG: info
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      # https://rustwasm.github.io/wasm-pack/installer/
      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build wasm package
        env:
          RUSTFLAGS: '-C target-feature=+simd128 --cfg getrandom_backend="wasm_js"'
        run: wasm-pack build libDF --target web --release --no-opt -- --features wasm --no-default-features

      - uses: actions/upload-artifact@v4
        with:
          name: wasm_package
          path: ./libDF/pkg
          retention-days: 7